name: Dataset Build

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'datasets/**'

jobs:
  build-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python datasets/pipeline/build.py --version 20250101.1 --sources datasets/raw/*.txt --out datasets
      - run: |
          echo "Generated files:" && ls -la datasets/v20250101.1 || true


